[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#2d353b"
foreground = "#83C092"
dim_foreground = "#a7c080"
bright_foreground = "#f2efdf"

[colors.cursor]
text = "#1e1e2e"
cursor = "#83c092"

[colors.vi_mode_cursor]
text = "#83c092"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#5c6a72"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#5c6a72"
background = "#a6adc8"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#232a2e"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#7fbbb3"
white = "#ffffff"

[colors.bright]
black = "#232a2e"
red = "#f85552"
green = "#8da101"
yellow = "#dfa000"
blue = "#3a94c5"
cyan = "#35a77c"
white = "#ffffff"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"
