general.import = ["./theme.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20

decorations = "Buttonless"
opacity = 1
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 16


